# -*- coding: utf-8 -*-
"""datajarlabs 2.4 ödevi

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/101mxcjeuJtK_uqxE5fy8TJlhr6wZNjm2
"""

#2.4.1 Ödevi
a=int(input("derece giriniz:"))
if a!=[]:
  c=(a-32)*5/9
  f = (a*9/5)+32
t=["{}F".format(a),"-->","{:.1f}C".format(c)],["{}C".format(a),"-->","{:.1f}F".format(f)]
print(*t)

#2.4.2 Ödevi

word=input("Ters çevirilecek kelimeyi girin: ")
reverse=""

for i in range(len(word)):
    reverse+=word[len(word)-i-1]

print(reverse)

#2.4.3 Ödevi

fb=[]
num=1

while num<50:
    if num<=2:
        fb.append(1)
        
    else:
        a=fb[-2]+fb[-1]
        if a<50:
            fb.append(a)
    
    num+=1
    
print(fb)

#2.4.4 Ödevi
sayı=int(input("Çarpım tablosu için bir sayı girin"))
for i in range(1, 11):
   print(sayı,'x', i,'=',sayı*i)

#2.4.5 Ödevi

sayilar=[i**3 if i%2==0 else i**2 for i in range(1,21)]

sayilar