# -*- coding: utf-8 -*-
"""evren_sahin_veri_yapıları_ödevi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n0_pvdxA6UnnM39SbT-lK6Xv-0RmGHbv
"""

#Bölüm 2.3 soru 1 cevabı
gunler = {
    1: "pazartesi",
    2: "salı",
    3: "çarşamba",
    4: "perşembe",
    5: "cuma",
    6: "cumartesi",
    7: "pazar"
    }
print("gunler:",gunler)
a=int(input("silmek istediğiniz 1. gün numarasını girin:"))
b=int(input("silmek istediğiniz 2. gün numarasını girin:"))

del gunler[a]
del gunler[b]
print(gunler)


#Bölüm 2.3 soru 2 cevabı

aylar = [["ocak",31],["şubat",28],["mart",31],["nisan",30],["mayıs",31],["haziran",30],["temmuz",31],["ağustos",31],["eylül",30],["ekim",31],["kasım",30],["aralık",31]]

print(aylar)

#Bölüm 2.3 soru 3 cevabı

print([aylar[0][0],aylar[1][0],aylar[2][0],aylar[3][0],aylar[4][0],aylar[5][0],aylar[6][0],aylar[7][0],aylar[8][0],aylar[9][0],aylar[10][0],aylar[11][0]],
      [aylar[0][1],aylar[1][1],aylar[2][1],aylar[3][1],aylar[4][1],aylar[5][1],aylar[6][1],aylar[7][1],aylar[8][1],aylar[9][1],aylar[10][1],aylar[11][1]],
      "\n")

#Bölüm 2.3 soru 4 cevabı

ilkbahar = [aylar[2][0],aylar[3][0],aylar[4][0]]
yaz = [aylar[5][0],aylar[6][0],aylar[7][0]]
sonbahar = [aylar[8][0],aylar[9][0],aylar[10][0]]
kış = [aylar[11][0],aylar[0][0],aylar[1][0]]
print("ilkbahar ayları:",ilkbahar)
print("yaz ayları:",yaz)
print("sonbahar ayları:",sonbahar)
print("kış ayları:",kış)

#Bölüm 2.3 soru 5 cevabı

yaz_mevsimi_gün_uzunluğu = aylar[5][1]+aylar[6][1]+aylar[7][1]
print(yaz_mevsimi_gün_uzunluğu)