# -*- coding: utf-8 -*-
"""Evren Şahin - Python Temelleri Ödevi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uAeR3qRp0m_Cl1zNiRHYZyYia34rHe1Q
"""

#Ödev1
x=1000
y=7
t=12
z=x*(1+(t/100))**y
print(z)

#ödev2
a='Hafta başında {} dolarlık bitcoin aldığımızda \n günde ortalama %{} kazançla, \n bir hafta sonunda {:.2f} dolar kazanırdık'.format(x,t,z-x)
print(a)

#ödev3
r = input('Dosya Adı Giriniz:')
print ('Dosya Adınız: {}.py'.format(r))